Wukong's Review
Croissant-Team-Cinnamon-Bootcamp-2024/homework-week-1 pull request #30
Opened 2024-07-03 14:28 UTC by 21522173huy

- The line : python scripts/run.py -f assets/ocr-test.pdf can not be used, and I have to relocate file run.py into src folder and change the code to python src/run.py -f assets/ocr-test.pdf
- The results have been overwritten (I added two files into the running script respectively, and the second results would be overwritten on the first one)
- The code seem can not handle docx file
- The upload function might have some troubles. Particularly i tried two different keys, but there still be errors

2024-07-03 15:09 UTC, micache commented
> * The line: python scripts/run.py -f assets/ocr-test.pdf cannot be used, and I have to relocate file run.py into src folder and change the code to python src/run.py -f assets/ocr-test.pdf
> * The results have been overwritten (I added two files into the running script respectively, and the second result would be overwritten on the first one)
> * The code seem cannot handle docx file
> * The upload function might have some troubles. Particularly, i tried two different keys, but there still be errors

2024-07-03 17:54 UTC, hoang1645 requested changes
Looks like you did not see my review, so I am gonna copy it verbatim here; also you don't need to create a new PR to fix an issue, just push the commits and it will go into the PR. Anyway:
- Docstrings found only for some classes, and none for their methods. Maybe I am being pedantic but I would like to request docstrings for all classes and if possible, their methods as well
- Also please add the version annotations for requirements.txt.

2024-07-05 04:19 UTC, thaohp113 commented
> Looks like you did not see my review, so I am gonna copy it verbatim here; also you don't need to create a new PR to fix an issue, just push the commits and it will go into the PR. Anyway:
> 
> * Docstrings found only for some classes, and none for their methods. Maybe I am being pedantic but I would like to request docstrings for all classes and if possible, their methods as well
> * Also please add the version annotations for requirements.txt.

addressed! thanks for the suggestion

2024-07-05 07:04 UTC, hoang1645 approved these changes

2024-07-05 07:07 UTC, NamSee04 approved these changes

2024-07-05 07:07 UTC, Qcymaq approved these changes

2024-07-05 07:14 UTC, closed without merging