Adding detector and recognizer modules with corresponding unittest
Croissant-Team-Cinnamon-Bootcamp-2024/homework-week-1 pull request #5
Opened 2024-06-29 15:54 UTC by hungpham3112

NEED TO REVIEW BEFORE MERGE TO DEV BRANCH

2024-06-29 16:17 UTC, Huy1711 requested changes
Good code, but please take a look at my comments before merge

2024-06-29 16:17 UTC, Huy1711 commented on model/test_detector.py
Please put test file inside `/test` folder

2024-06-29 16:17 UTC, Huy1711 commented on model/detector.py
please put this file inside src/model folder

2024-06-29 16:17 UTC, Huy1711 commented on model/__init__.py
please put this file inside src/model folder

2024-06-29 16:17 UTC, Huy1711 commented on model/recognizer.py
please put this file inside src/model folder

2024-06-29 16:17 UTC, Huy1711 commented on model/test_recognizer.py
please put this file inside test/ folder

2024-06-29 16:17 UTC, Huy1711 commented on model/detector.py
> +    def resize_image(self, image: Image.Image, max_size: tuple = (2000, 2000)) -> tuple:
You can use return type hint like this:

from typing import Tuple

def resize_image(...) -> Tuple[Image, float]:

2024-06-29 16:17 UTC, Huy1711 commented on model/recognizer.py
> +    def __init__(self):
you can delete this function if you don't implement it

2024-06-30 04:57 UTC, micache approved these changes
LGTM

2024-06-30 08:00 UTC, closed without merging